Assignment No : 02

Roll no : 13204

Contents for Theory:1. Creation of Dataset using Microsoft Excel.3. Identification and Handling of Outliers

In [1]:
import pandas as pd

In [2]:
df=pd.read_csv("C:/Users\/AJAY/Desktop/Student_Performance.csv")

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 6 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Math_Score              45 non-null     float64
 1   Reading_Score           46 non-null     float64
 2   Writing_Score           47 non-null     float64
 3   Placement_Score         45 non-null     float64
 4   Club_Join_Date          47 non-null     float64
 5    Placement_Offer_Count  46 non-null     float64
dtypes: float64(6)
memory usage: 2.5 KB

In [4]:
df.fillna(23)

,Math_Score,Reading_Score,Writing_Score,Placement_Score,Club_Join_Date,Placement_Offer_Count
0,72.0,84.0,76.0,90.0,456.0,3.0
1,62.0,82.0,65.0,87.0,2019.0,3.0
2,58.0,22.0,0.0,83.0,2021.0,6.0
3,69.0,45.0,75.0,98.0,2021.0,3.0
4,99.0,81.0,64.0,80.0,23.0,2.0
5,63.0,79.0,79.0,91.0,2021.0,9.0
6,68.0,78.0,0.0,92.0,2020.0,3.0
7,68.0,88.0,80.0,79.0,90.0,2.0
8,23.0,75.0,62.0,86.0,2021.0,3.0
9,23.0,85.0,66.0,23.0,2018.0,2.0
10,68.0,86.0,66.0,80.0,999.0,2.0
11,23.0,84.0,72.0,77.0,2018.0,2.0
12,23.0,94.0,66.0,90.0,2020.0,3.0
13,34.0,75.0,66.0,95.0,0.0,0.0
14,75.0,75.0,72.0,96.0,2019.0,3.0
15,23.0,83.0,62.0,23.0,2021.0,2.0
16,60.0,23.0,73.0,23.0,2020.0,2.0
17,1.0,76.0,60.0,23.0,2020.0,3.0
18,80.0,23.0,65.0,23.0,2021.0,2.0
19,79.0,93.0,3.0,80.0,2021.0,2.0
20,79.0,23.0,76.0,77.0,2019.0,90.0
21,67.0,4.0,80.0,97.0,2021.0,3.0
22,64.0,93.0,3.0,98.0,2018.0,3.0
23,0.0,75.0,77.0,80.0,2018.0,2.0
24,72.0,23.0,67.0,87.0,23.0,3.0
25,74.0,87.0,72.0,98.0,2020.0,3.0
26,71.0,78.0,72.0,78.0,23.0,2.0
27,72.0,90.0,73.0,82.0,2021.0,2.0
28,72.0,91.0,67.0,87.0,2020.0,3.0
29,65.0,79.0,64.0,91.0,2019.0,3.0
30,73.0,95.0,23.0,93.0,2019.0,3.0
31,62.0,91.0,23.0,98.0,2019.0,3.0
32,76.0,91.0,23.0,93.0,89.0,3.0
33,73.0,84.0,72.0,90.0,2021.0,3.0
34,71.0,92.0,67.0,89.0,2019.0,3.0
35,65.0,85.0,78.0,81.0,2018.0,2.0
36,75.0,95.0,77.0,99.0,2018.0,3.0
37,61.0,76.0,73.0,97.0,2020.0,3.0
38,63.0,79.0,76.0,86.0,3445.0,3.0
39,67.0,5444.0,60.0,80.0,2020.0,2.0
40,70.0,89.0,67.0,82.0,2020.0,2.0
41,61.0,94.0,62.0,88.0,2021.0,3.0
42,64.0,95.0,63.0,98.0,2020.0,23.0
43,69.0,95.0,60.0,5.0,2019.0,23.0
44,69.0,78.0,999.0,77.0,2019.0,23.0
45,62.0,83.0,63.0,81.0,2020.0,23.0
46,68.0,80.0,73.0,0.0,2019.0,1.0
47,73.0,92.0,73.0,81.0,2019.0,2.0
48,74.0,75.0,99.0,100.0,99.0,3.0
49,75.0,76.0,0.0,80.0,2018.0,2.0

In [5]:
df.min

<bound method DataFrame.min of     Math_Score  Reading_Score  Writing_Score  Placement_Score  Club_Join_Date  \
0         72.0           84.0           76.0             90.0           456.0
1         62.0           82.0           65.0             87.0          2019.0
2         58.0           22.0            0.0             83.0          2021.0
3         69.0           45.0           75.0             98.0          2021.0
4         99.0           81.0           64.0             80.0             NaN
5         63.0           79.0           79.0             91.0          2021.0
6         68.0           78.0            0.0             92.0          2020.0
7         68.0           88.0           80.0             79.0            90.0
8          NaN           75.0           62.0             86.0          2021.0
9          NaN           85.0           66.0              NaN          2018.0
10        68.0           86.0           66.0             80.0           999.0
11         NaN           84.0           72.0             77.0          2018.0
12         NaN           94.0           66.0             90.0          2020.0
13        34.0           75.0           66.0             95.0             0.0
14        75.0           75.0           72.0             96.0          2019.0
15         NaN           83.0           62.0              NaN          2021.0
16        60.0            NaN           73.0              NaN          2020.0
17         1.0           76.0           60.0              NaN          2020.0
18        80.0            NaN           65.0              NaN          2021.0
19        79.0           93.0            3.0             80.0          2021.0
20        79.0            NaN           76.0             77.0          2019.0
21        67.0            4.0           80.0             97.0          2021.0
22        64.0           93.0            3.0             98.0          2018.0
23         0.0           75.0           77.0             80.0          2018.0
24        72.0            NaN           67.0             87.0             NaN
25        74.0           87.0           72.0             98.0          2020.0
26        71.0           78.0           72.0             78.0             NaN
27        72.0           90.0           73.0             82.0          2021.0
28        72.0           91.0           67.0             87.0          2020.0
29        65.0           79.0           64.0             91.0          2019.0
30        73.0           95.0            NaN             93.0          2019.0
31        62.0           91.0            NaN             98.0          2019.0
32        76.0           91.0            NaN             93.0            89.0
33        73.0           84.0           72.0             90.0          2021.0
34        71.0           92.0           67.0             89.0          2019.0
35        65.0           85.0           78.0             81.0          2018.0
36        75.0           95.0           77.0             99.0          2018.0
37        61.0           76.0           73.0             97.0          2020.0
38        63.0           79.0           76.0             86.0          3445.0
39        67.0         5444.0           60.0             80.0          2020.0
40        70.0           89.0           67.0             82.0          2020.0
41        61.0           94.0           62.0             88.0          2021.0
42        64.0           95.0           63.0             98.0          2020.0
43        69.0           95.0           60.0              5.0          2019.0
44        69.0           78.0          999.0             77.0          2019.0
45        62.0           83.0           63.0             81.0          2020.0
46        68.0           80.0           73.0              0.0          2019.0
47        73.0           92.0           73.0             81.0          2019.0
48        74.0           75.0           99.0            100.0            99.0
49        75.0           76.0            0.0             80.0          2018.0

     Placement_Offer_Count
0                      3.0
1                      3.0
2                      6.0
3                      3.0
4                      2.0
5                      9.0
6                      3.0
7                      2.0
8                      3.0
9                      2.0
10                     2.0
11                     2.0
12                     3.0
13                     0.0
14                     3.0
15                     2.0
16                     2.0
17                     3.0
18                     2.0
19                     2.0
20                    90.0
21                     3.0
22                     3.0
23                     2.0
24                     3.0
25                     3.0
26                     2.0
27                     2.0
28                     3.0
29                     3.0
30                     3.0
31                     3.0
32                     3.0
33                     3.0
34                     3.0
35                     2.0
36                     3.0
37                     3.0
38                     3.0
39                     2.0
40                     2.0
41                     3.0
42                     NaN
43                     NaN
44                     NaN
45                     NaN
46                     1.0
47                     2.0
48                     3.0
49                     2.0  >

In [6]:
df.tail(5)

,Math_Score,Reading_Score,Writing_Score,Placement_Score,Club_Join_Date,Placement_Offer_Count
45,62.0,83.0,63.0,81.0,2020.0,NaN
46,68.0,80.0,73.0,0.0,2019.0,1.0
47,73.0,92.0,73.0,81.0,2019.0,2.0
48,74.0,75.0,99.0,100.0,99.0,3.0
49,75.0,76.0,0.0,80.0,2018.0,2.0

In [7]:
df.head(5)

,Math_Score,Reading_Score,Writing_Score,Placement_Score,Club_Join_Date,Placement_Offer_Count
0,72.0,84.0,76.0,90.0,456.0,3.0
1,62.0,82.0,65.0,87.0,2019.0,3.0
2,58.0,22.0,0.0,83.0,2021.0,6.0
3,69.0,45.0,75.0,98.0,2021.0,3.0
4,99.0,81.0,64.0,80.0,NaN,2.0

In [8]:
df.describe()

,Math_Score,Reading_Score,Writing_Score,Placement_Score,Club_Join_Date,Placement_Offer_Count
count,45.000000,46.000000,47.000000,45.000000,47.000000,46.000000
mean,65.844444,197.195652,82.659574,83.933333,1829.021277,4.608696
std,16.737214,790.976601,138.429118,19.193275,643.179753,12.931406
min,0.000000,4.000000,0.000000,0.000000,0.000000,0.000000
25%,63.000000,78.000000,63.000000,80.000000,2018.000000,2.000000
50%,69.000000,84.000000,67.000000,87.000000,2019.000000,3.000000
75%,73.000000,91.000000,74.000000,93.000000,2020.500000,3.000000
max,99.000000,5444.000000,999.000000,100.000000,3445.000000,90.000000

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 6 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Math_Score              45 non-null     float64
 1   Reading_Score           46 non-null     float64
 2   Writing_Score           47 non-null     float64
 3   Placement_Score         45 non-null     float64
 4   Club_Join_Date          47 non-null     float64
 5    Placement_Offer_Count  46 non-null     float64
dtypes: float64(6)
memory usage: 2.5 KB

In [10]:
df

,Math_Score,Reading_Score,Writing_Score,Placement_Score,Club_Join_Date,Placement_Offer_Count
0,72.0,84.0,76.0,90.0,456.0,3.0
1,62.0,82.0,65.0,87.0,2019.0,3.0
2,58.0,22.0,0.0,83.0,2021.0,6.0
3,69.0,45.0,75.0,98.0,2021.0,3.0
4,99.0,81.0,64.0,80.0,NaN,2.0
5,63.0,79.0,79.0,91.0,2021.0,9.0
6,68.0,78.0,0.0,92.0,2020.0,3.0
7,68.0,88.0,80.0,79.0,90.0,2.0
8,NaN,75.0,62.0,86.0,2021.0,3.0
9,NaN,85.0,66.0,NaN,2018.0,2.0
10,68.0,86.0,66.0,80.0,999.0,2.0
11,NaN,84.0,72.0,77.0,2018.0,2.0
12,NaN,94.0,66.0,90.0,2020.0,3.0
13,34.0,75.0,66.0,95.0,0.0,0.0
14,75.0,75.0,72.0,96.0,2019.0,3.0
15,NaN,83.0,62.0,NaN,2021.0,2.0
16,60.0,NaN,73.0,NaN,2020.0,2.0
17,1.0,76.0,60.0,NaN,2020.0,3.0
18,80.0,NaN,65.0,NaN,2021.0,2.0
19,79.0,93.0,3.0,80.0,2021.0,2.0
20,79.0,NaN,76.0,77.0,2019.0,90.0
21,67.0,4.0,80.0,97.0,2021.0,3.0
22,64.0,93.0,3.0,98.0,2018.0,3.0
23,0.0,75.0,77.0,80.0,2018.0,2.0
24,72.0,NaN,67.0,87.0,NaN,3.0
25,74.0,87.0,72.0,98.0,2020.0,3.0
26,71.0,78.0,72.0,78.0,NaN,2.0
27,72.0,90.0,73.0,82.0,2021.0,2.0
28,72.0,91.0,67.0,87.0,2020.0,3.0
29,65.0,79.0,64.0,91.0,2019.0,3.0
30,73.0,95.0,NaN,93.0,2019.0,3.0
31,62.0,91.0,NaN,98.0,2019.0,3.0
32,76.0,91.0,NaN,93.0,89.0,3.0
33,73.0,84.0,72.0,90.0,2021.0,3.0
34,71.0,92.0,67.0,89.0,2019.0,3.0
35,65.0,85.0,78.0,81.0,2018.0,2.0
36,75.0,95.0,77.0,99.0,2018.0,3.0
37,61.0,76.0,73.0,97.0,2020.0,3.0
38,63.0,79.0,76.0,86.0,3445.0,3.0
39,67.0,5444.0,60.0,80.0,2020.0,2.0
40,70.0,89.0,67.0,82.0,2020.0,2.0
41,61.0,94.0,62.0,88.0,2021.0,3.0
42,64.0,95.0,63.0,98.0,2020.0,NaN
43,69.0,95.0,60.0,5.0,2019.0,NaN
44,69.0,78.0,999.0,77.0,2019.0,NaN
45,62.0,83.0,63.0,81.0,2020.0,NaN
46,68.0,80.0,73.0,0.0,2019.0,1.0
47,73.0,92.0,73.0,81.0,2019.0,2.0
48,74.0,75.0,99.0,100.0,99.0,3.0
49,75.0,76.0,0.0,80.0,2018.0,2.0

In [12]:
df.Math_Score.fillna(67)

0     72.0
1     62.0
2     58.0
3     69.0
4     99.0
5     63.0
6     68.0
7     68.0
8     67.0
9     67.0
10    68.0
11    67.0
12    67.0
13    34.0
14    75.0
15    67.0
16    60.0
17     1.0
18    80.0
19    79.0
20    79.0
21    67.0
22    64.0
23     0.0
24    72.0
25    74.0
26    71.0
27    72.0
28    72.0
29    65.0
30    73.0
31    62.0
32    76.0
33    73.0
34    71.0
35    65.0
36    75.0
37    61.0
38    63.0
39    67.0
40    70.0
41    61.0
42    64.0
43    69.0
44    69.0
45    62.0
46    68.0
47    73.0
48    74.0
49    75.0
Name: Math_Score, dtype: float64

In [13]:
df.columns.values

array(['Math_Score', 'Reading_Score', 'Writing_Score', 'Placement_Score',
       'Club_Join_Date', ' Placement_Offer_Count'], dtype=object)

In [14]:
df.iloc[20]

Math_Score                  79.0
Reading_Score                NaN
Writing_Score               76.0
Placement_Score             77.0
Club_Join_Date            2019.0
 Placement_Offer_Count      90.0
Name: 20, dtype: float64

In [15]:
df.iloc[:,2:5]

    Writing_Score  Placement_Score  Club_Join_Date
0            76.0             90.0           456.0
1            65.0             87.0          2019.0
2             0.0             83.0          2021.0
3            75.0             98.0          2021.0
4            64.0             80.0             NaN
5            79.0             91.0          2021.0
6             0.0             92.0          2020.0
7            80.0             79.0            90.0
8            62.0             86.0          2021.0
9            66.0              NaN          2018.0
10           66.0             80.0           999.0
11           72.0             77.0          2018.0
12           66.0             90.0          2020.0
13           66.0             95.0             0.0
14           72.0             96.0          2019.0
15           62.0              NaN          2021.0
16           73.0              NaN          2020.0
17           60.0              NaN          2020.0
18           65.0              NaN          2021.0
19            3.0             80.0          2021.0
20           76.0             77.0          2019.0
21           80.0             97.0          2021.0
22            3.0             98.0          2018.0
23           77.0             80.0          2018.0
24           67.0             87.0             NaN
25           72.0             98.0          2020.0
26           72.0             78.0             NaN
27           73.0             82.0          2021.0
28           67.0             87.0          2020.0
29           64.0             91.0          2019.0
30            NaN             93.0          2019.0
31            NaN             98.0          2019.0
32            NaN             93.0            89.0
33           72.0             90.0          2021.0
34           67.0             89.0          2019.0
35           78.0             81.0          2018.0
36           77.0             99.0          2018.0
37           73.0             97.0          2020.0
38           76.0             86.0          3445.0
39           60.0             80.0          2020.0
40           67.0             82.0          2020.0
41           62.0             88.0          2021.0
42           63.0             98.0          2020.0
43           60.0              5.0          2019.0
44          999.0             77.0          2019.0
45           63.0             81.0          2020.0
46           73.0              0.0          2019.0
47           73.0             81.0          2019.0
48           99.0            100.0            99.0
49            0.0             80.0          2018.0

In [17]:
df.Math_Score.fillna(67, inplace=True)

C:\Users\AJAY\AppData\Local\Temp\ipykernel_13756\1043155260.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df.Math_Score.fillna(67, inplace=True)

In [19]:
df['Math_Score'] = df['Math_Score'].fillna(67)

In [20]:
df.Math_Score.isna().sum()

np.int64(0)

In [21]:
df

,Math_Score,Reading_Score,Writing_Score,Placement_Score,Club_Join_Date,Placement_Offer_Count
0,72.0,84.0,76.0,90.0,456.0,3.0
1,62.0,82.0,65.0,87.0,2019.0,3.0
2,58.0,22.0,0.0,83.0,2021.0,6.0
3,69.0,45.0,75.0,98.0,2021.0,3.0
4,99.0,81.0,64.0,80.0,NaN,2.0
5,63.0,79.0,79.0,91.0,2021.0,9.0
6,68.0,78.0,0.0,92.0,2020.0,3.0
7,68.0,88.0,80.0,79.0,90.0,2.0
8,67.0,75.0,62.0,86.0,2021.0,3.0
9,67.0,85.0,66.0,NaN,2018.0,2.0
10,68.0,86.0,66.0,80.0,999.0,2.0
11,67.0,84.0,72.0,77.0,2018.0,2.0
12,67.0,94.0,66.0,90.0,2020.0,3.0
13,34.0,75.0,66.0,95.0,0.0,0.0
14,75.0,75.0,72.0,96.0,2019.0,3.0
15,67.0,83.0,62.0,NaN,2021.0,2.0
16,60.0,NaN,73.0,NaN,2020.0,2.0
17,1.0,76.0,60.0,NaN,2020.0,3.0
18,80.0,NaN,65.0,NaN,2021.0,2.0
19,79.0,93.0,3.0,80.0,2021.0,2.0
20,79.0,NaN,76.0,77.0,2019.0,90.0
21,67.0,4.0,80.0,97.0,2021.0,3.0
22,64.0,93.0,3.0,98.0,2018.0,3.0
23,0.0,75.0,77.0,80.0,2018.0,2.0
24,72.0,NaN,67.0,87.0,NaN,3.0
25,74.0,87.0,72.0,98.0,2020.0,3.0
26,71.0,78.0,72.0,78.0,NaN,2.0
27,72.0,90.0,73.0,82.0,2021.0,2.0
28,72.0,91.0,67.0,87.0,2020.0,3.0
29,65.0,79.0,64.0,91.0,2019.0,3.0
30,73.0,95.0,NaN,93.0,2019.0,3.0
31,62.0,91.0,NaN,98.0,2019.0,3.0
32,76.0,91.0,NaN,93.0,89.0,3.0
33,73.0,84.0,72.0,90.0,2021.0,3.0
34,71.0,92.0,67.0,89.0,2019.0,3.0
35,65.0,85.0,78.0,81.0,2018.0,2.0
36,75.0,95.0,77.0,99.0,2018.0,3.0
37,61.0,76.0,73.0,97.0,2020.0,3.0
38,63.0,79.0,76.0,86.0,3445.0,3.0
39,67.0,5444.0,60.0,80.0,2020.0,2.0
40,70.0,89.0,67.0,82.0,2020.0,2.0
41,61.0,94.0,62.0,88.0,2021.0,3.0
42,64.0,95.0,63.0,98.0,2020.0,NaN
43,69.0,95.0,60.0,5.0,2019.0,NaN
44,69.0,78.0,999.0,77.0,2019.0,NaN
45,62.0,83.0,63.0,81.0,2020.0,NaN
46,68.0,80.0,73.0,0.0,2019.0,1.0
47,73.0,92.0,73.0,81.0,2019.0,2.0
48,74.0,75.0,99.0,100.0,99.0,3.0
49,75.0,76.0,0.0,80.0,2018.0,2.0