Assingment No : 2

Roll No. : 13204

In [1]:
import pandas as pd

In [2]:
df =pd.read_csv("C:/Users/AJAY/Desktop/Student_Performance.csv")

In [3]:
df

,Math_Score,Reading_Score,Writing_Score,Placement_Score,Club_Join_Date,Placement_Offer_Count
0,72.0,84.0,76.0,90.0,456.0,3.0
1,62.0,82.0,65.0,87.0,2019.0,3.0
2,58.0,22.0,0.0,83.0,2021.0,6.0
3,69.0,45.0,75.0,98.0,2021.0,3.0
4,99.0,81.0,64.0,80.0,NaN,2.0
5,63.0,79.0,79.0,91.0,2021.0,9.0
6,68.0,78.0,0.0,92.0,2020.0,3.0
7,68.0,88.0,80.0,79.0,90.0,2.0
8,NaN,75.0,62.0,86.0,2021.0,3.0
9,NaN,85.0,66.0,NaN,2018.0,2.0
10,68.0,86.0,66.0,80.0,999.0,2.0
11,NaN,84.0,72.0,77.0,2018.0,2.0
12,NaN,94.0,66.0,90.0,2020.0,3.0
13,34.0,75.0,66.0,95.0,0.0,0.0
14,75.0,75.0,72.0,96.0,2019.0,3.0
15,NaN,83.0,62.0,NaN,2021.0,2.0
16,60.0,NaN,73.0,NaN,2020.0,2.0
17,1.0,76.0,60.0,NaN,2020.0,3.0
18,80.0,NaN,65.0,NaN,2021.0,2.0
19,79.0,93.0,3.0,80.0,2021.0,2.0
20,79.0,NaN,76.0,77.0,2019.0,90.0
21,67.0,4.0,80.0,97.0,2021.0,3.0
22,64.0,93.0,3.0,98.0,2018.0,3.0
23,0.0,75.0,77.0,80.0,2018.0,2.0
24,72.0,NaN,67.0,87.0,NaN,3.0
25,74.0,87.0,72.0,98.0,2020.0,3.0
26,71.0,78.0,72.0,78.0,NaN,2.0
27,72.0,90.0,73.0,82.0,2021.0,2.0
28,72.0,91.0,67.0,87.0,2020.0,3.0
29,65.0,79.0,64.0,91.0,2019.0,3.0
30,73.0,95.0,NaN,93.0,2019.0,3.0
31,62.0,91.0,NaN,98.0,2019.0,3.0
32,76.0,91.0,NaN,93.0,89.0,3.0
33,73.0,84.0,72.0,90.0,2021.0,3.0
34,71.0,92.0,67.0,89.0,2019.0,3.0
35,65.0,85.0,78.0,81.0,2018.0,2.0
36,75.0,95.0,77.0,99.0,2018.0,3.0
37,61.0,76.0,73.0,97.0,2020.0,3.0
38,63.0,79.0,76.0,86.0,3445.0,3.0
39,67.0,5444.0,60.0,80.0,2020.0,2.0
40,70.0,89.0,67.0,82.0,2020.0,2.0
41,61.0,94.0,62.0,88.0,2021.0,3.0
42,64.0,95.0,63.0,98.0,2020.0,NaN
43,69.0,95.0,60.0,5.0,2019.0,NaN
44,69.0,78.0,999.0,77.0,2019.0,NaN
45,62.0,83.0,63.0,81.0,2020.0,NaN
46,68.0,80.0,73.0,0.0,2019.0,1.0
47,73.0,92.0,73.0,81.0,2019.0,2.0
48,74.0,75.0,99.0,100.0,99.0,3.0
49,75.0,76.0,0.0,80.0,2018.0,2.0

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 6 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Math_Score              45 non-null     float64
 1   Reading_Score           46 non-null     float64
 2   Writing_Score           47 non-null     float64
 3   Placement_Score         45 non-null     float64
 4   Club_Join_Date          47 non-null     float64
 5    Placement_Offer_Count  46 non-null     float64
dtypes: float64(6)
memory usage: 2.5 KB

In [5]:
df.isnull()

,Math_Score,Reading_Score,Writing_Score,Placement_Score,Club_Join_Date,Placement_Offer_Count
0,False,False,False,False,False,False
1,False,False,False,False,False,False
2,False,False,False,False,False,False
3,False,False,False,False,False,False
4,False,False,False,False,True,False
5,False,False,False,False,False,False
6,False,False,False,False,False,False
7,False,False,False,False,False,False
8,True,False,False,False,False,False
9,True,False,False,True,False,False
10,False,False,False,False,False,False
11,True,False,False,False,False,False
12,True,False,False,False,False,False
13,False,False,False,False,False,False
14,False,False,False,False,False,False
15,True,False,False,True,False,False
16,False,True,False,True,False,False
17,False,False,False,True,False,False
18,False,True,False,True,False,False
19,False,False,False,False,False,False
20,False,True,False,False,False,False
21,False,False,False,False,False,False
22,False,False,False,False,False,False
23,False,False,False,False,False,False
24,False,True,False,False,True,False
25,False,False,False,False,False,False
26,False,False,False,False,True,False
27,False,False,False,False,False,False
28,False,False,False,False,False,False
29,False,False,False,False,False,False
30,False,False,True,False,False,False
31,False,False,True,False,False,False
32,False,False,True,False,False,False
33,False,False,False,False,False,False
34,False,False,False,False,False,False
35,False,False,False,False,False,False
36,False,False,False,False,False,False
37,False,False,False,False,False,False
38,False,False,False,False,False,False
39,False,False,False,False,False,False
40,False,False,False,False,False,False
41,False,False,False,False,False,False
42,False,False,False,False,False,True
43,False,False,False,False,False,True
44,False,False,False,False,False,True
45,False,False,False,False,False,True
46,False,False,False,False,False,False
47,False,False,False,False,False,False
48,False,False,False,False,False,False
49,False,False,False,False,False,False

In [6]:

series = pd.isnull(df["Math_Score"]) 
df[series]

,Math_Score,Reading_Score,Writing_Score,Placement_Score,Club_Join_Date,Placement_Offer_Count
8,NaN,75.0,62.0,86.0,2021.0,3.0
9,NaN,85.0,66.0,NaN,2018.0,2.0
11,NaN,84.0,72.0,77.0,2018.0,2.0
12,NaN,94.0,66.0,90.0,2020.0,3.0
15,NaN,83.0,62.0,NaN,2021.0,2.0

In [7]:
df.notnull()

,Math_Score,Reading_Score,Writing_Score,Placement_Score,Club_Join_Date,Placement_Offer_Count
0,True,True,True,True,True,True
1,True,True,True,True,True,True
2,True,True,True,True,True,True
3,True,True,True,True,True,True
4,True,True,True,True,False,True
5,True,True,True,True,True,True
6,True,True,True,True,True,True
7,True,True,True,True,True,True
8,False,True,True,True,True,True
9,False,True,True,False,True,True
10,True,True,True,True,True,True
11,False,True,True,True,True,True
12,False,True,True,True,True,True
13,True,True,True,True,True,True
14,True,True,True,True,True,True
15,False,True,True,False,True,True
16,True,False,True,False,True,True
17,True,True,True,False,True,True
18,True,False,True,False,True,True
19,True,True,True,True,True,True
20,True,False,True,True,True,True
21,True,True,True,True,True,True
22,True,True,True,True,True,True
23,True,True,True,True,True,True
24,True,False,True,True,False,True
25,True,True,True,True,True,True
26,True,True,True,True,False,True
27,True,True,True,True,True,True
28,True,True,True,True,True,True
29,True,True,True,True,True,True
30,True,True,False,True,True,True
31,True,True,False,True,True,True
32,True,True,False,True,True,True
33,True,True,True,True,True,True
34,True,True,True,True,True,True
35,True,True,True,True,True,True
36,True,True,True,True,True,True
37,True,True,True,True,True,True
38,True,True,True,True,True,True
39,True,True,True,True,True,True
40,True,True,True,True,True,True
41,True,True,True,True,True,True
42,True,True,True,True,True,False
43,True,True,True,True,True,False
44,True,True,True,True,True,False
45,True,True,True,True,True,False
46,True,True,True,True,True,True
47,True,True,True,True,True,True
48,True,True,True,True,True,True
49,True,True,True,True,True,True

In [8]:
series1 = pd.notnull(df["Math_Score"]) 
df[series1]

,Math_Score,Reading_Score,Writing_Score,Placement_Score,Club_Join_Date,Placement_Offer_Count
0,72.0,84.0,76.0,90.0,456.0,3.0
1,62.0,82.0,65.0,87.0,2019.0,3.0
2,58.0,22.0,0.0,83.0,2021.0,6.0
3,69.0,45.0,75.0,98.0,2021.0,3.0
4,99.0,81.0,64.0,80.0,NaN,2.0
5,63.0,79.0,79.0,91.0,2021.0,9.0
6,68.0,78.0,0.0,92.0,2020.0,3.0
7,68.0,88.0,80.0,79.0,90.0,2.0
10,68.0,86.0,66.0,80.0,999.0,2.0
13,34.0,75.0,66.0,95.0,0.0,0.0
14,75.0,75.0,72.0,96.0,2019.0,3.0
16,60.0,NaN,73.0,NaN,2020.0,2.0
17,1.0,76.0,60.0,NaN,2020.0,3.0
18,80.0,NaN,65.0,NaN,2021.0,2.0
19,79.0,93.0,3.0,80.0,2021.0,2.0
20,79.0,NaN,76.0,77.0,2019.0,90.0
21,67.0,4.0,80.0,97.0,2021.0,3.0
22,64.0,93.0,3.0,98.0,2018.0,3.0
23,0.0,75.0,77.0,80.0,2018.0,2.0
24,72.0,NaN,67.0,87.0,NaN,3.0
25,74.0,87.0,72.0,98.0,2020.0,3.0
26,71.0,78.0,72.0,78.0,NaN,2.0
27,72.0,90.0,73.0,82.0,2021.0,2.0
28,72.0,91.0,67.0,87.0,2020.0,3.0
29,65.0,79.0,64.0,91.0,2019.0,3.0
30,73.0,95.0,NaN,93.0,2019.0,3.0
31,62.0,91.0,NaN,98.0,2019.0,3.0
32,76.0,91.0,NaN,93.0,89.0,3.0
33,73.0,84.0,72.0,90.0,2021.0,3.0
34,71.0,92.0,67.0,89.0,2019.0,3.0
35,65.0,85.0,78.0,81.0,2018.0,2.0
36,75.0,95.0,77.0,99.0,2018.0,3.0
37,61.0,76.0,73.0,97.0,2020.0,3.0
38,63.0,79.0,76.0,86.0,3445.0,3.0
39,67.0,5444.0,60.0,80.0,2020.0,2.0
40,70.0,89.0,67.0,82.0,2020.0,2.0
41,61.0,94.0,62.0,88.0,2021.0,3.0
42,64.0,95.0,63.0,98.0,2020.0,NaN
43,69.0,95.0,60.0,5.0,2019.0,NaN
44,69.0,78.0,999.0,77.0,2019.0,NaN
45,62.0,83.0,63.0,81.0,2020.0,NaN
46,68.0,80.0,73.0,0.0,2019.0,1.0
47,73.0,92.0,73.0,81.0,2019.0,2.0
48,74.0,75.0,99.0,100.0,99.0,3.0
49,75.0,76.0,0.0,80.0,2018.0,2.0

In [9]:
ndf=df 
ndf.fillna(0)

,Math_Score,Reading_Score,Writing_Score,Placement_Score,Club_Join_Date,Placement_Offer_Count
0,72.0,84.0,76.0,90.0,456.0,3.0
1,62.0,82.0,65.0,87.0,2019.0,3.0
2,58.0,22.0,0.0,83.0,2021.0,6.0
3,69.0,45.0,75.0,98.0,2021.0,3.0
4,99.0,81.0,64.0,80.0,0.0,2.0
5,63.0,79.0,79.0,91.0,2021.0,9.0
6,68.0,78.0,0.0,92.0,2020.0,3.0
7,68.0,88.0,80.0,79.0,90.0,2.0
8,0.0,75.0,62.0,86.0,2021.0,3.0
9,0.0,85.0,66.0,0.0,2018.0,2.0
10,68.0,86.0,66.0,80.0,999.0,2.0
11,0.0,84.0,72.0,77.0,2018.0,2.0
12,0.0,94.0,66.0,90.0,2020.0,3.0
13,34.0,75.0,66.0,95.0,0.0,0.0
14,75.0,75.0,72.0,96.0,2019.0,3.0
15,0.0,83.0,62.0,0.0,2021.0,2.0
16,60.0,0.0,73.0,0.0,2020.0,2.0
17,1.0,76.0,60.0,0.0,2020.0,3.0
18,80.0,0.0,65.0,0.0,2021.0,2.0
19,79.0,93.0,3.0,80.0,2021.0,2.0
20,79.0,0.0,76.0,77.0,2019.0,90.0
21,67.0,4.0,80.0,97.0,2021.0,3.0
22,64.0,93.0,3.0,98.0,2018.0,3.0
23,0.0,75.0,77.0,80.0,2018.0,2.0
24,72.0,0.0,67.0,87.0,0.0,3.0
25,74.0,87.0,72.0,98.0,2020.0,3.0
26,71.0,78.0,72.0,78.0,0.0,2.0
27,72.0,90.0,73.0,82.0,2021.0,2.0
28,72.0,91.0,67.0,87.0,2020.0,3.0
29,65.0,79.0,64.0,91.0,2019.0,3.0
30,73.0,95.0,0.0,93.0,2019.0,3.0
31,62.0,91.0,0.0,98.0,2019.0,3.0
32,76.0,91.0,0.0,93.0,89.0,3.0
33,73.0,84.0,72.0,90.0,2021.0,3.0
34,71.0,92.0,67.0,89.0,2019.0,3.0
35,65.0,85.0,78.0,81.0,2018.0,2.0
36,75.0,95.0,77.0,99.0,2018.0,3.0
37,61.0,76.0,73.0,97.0,2020.0,3.0
38,63.0,79.0,76.0,86.0,3445.0,3.0
39,67.0,5444.0,60.0,80.0,2020.0,2.0
40,70.0,89.0,67.0,82.0,2020.0,2.0
41,61.0,94.0,62.0,88.0,2021.0,3.0
42,64.0,95.0,63.0,98.0,2020.0,0.0
43,69.0,95.0,60.0,5.0,2019.0,0.0
44,69.0,78.0,999.0,77.0,2019.0,0.0
45,62.0,83.0,63.0,81.0,2020.0,0.0
46,68.0,80.0,73.0,0.0,2019.0,1.0
47,73.0,92.0,73.0,81.0,2019.0,2.0
48,74.0,75.0,99.0,100.0,99.0,3.0
49,75.0,76.0,0.0,80.0,2018.0,2.0

In [10]:
m_v=df['Math_Score'].mean()
df['Math_Score'].fillna(value=m_v, inplace=True) 
df

C:\Users\AJAY\AppData\Local\Temp\ipykernel_2352\4049197348.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Math_Score'].fillna(value=m_v, inplace=True)

,Math_Score,Reading_Score,Writing_Score,Placement_Score,Club_Join_Date,Placement_Offer_Count
0,72.000000,84.0,76.0,90.0,456.0,3.0
1,62.000000,82.0,65.0,87.0,2019.0,3.0
2,58.000000,22.0,0.0,83.0,2021.0,6.0
3,69.000000,45.0,75.0,98.0,2021.0,3.0
4,99.000000,81.0,64.0,80.0,NaN,2.0
5,63.000000,79.0,79.0,91.0,2021.0,9.0
6,68.000000,78.0,0.0,92.0,2020.0,3.0
7,68.000000,88.0,80.0,79.0,90.0,2.0
8,65.844444,75.0,62.0,86.0,2021.0,3.0
9,65.844444,85.0,66.0,NaN,2018.0,2.0
10,68.000000,86.0,66.0,80.0,999.0,2.0
11,65.844444,84.0,72.0,77.0,2018.0,2.0
12,65.844444,94.0,66.0,90.0,2020.0,3.0
13,34.000000,75.0,66.0,95.0,0.0,0.0
14,75.000000,75.0,72.0,96.0,2019.0,3.0
15,65.844444,83.0,62.0,NaN,2021.0,2.0
16,60.000000,NaN,73.0,NaN,2020.0,2.0
17,1.000000,76.0,60.0,NaN,2020.0,3.0
18,80.000000,NaN,65.0,NaN,2021.0,2.0
19,79.000000,93.0,3.0,80.0,2021.0,2.0
20,79.000000,NaN,76.0,77.0,2019.0,90.0
21,67.000000,4.0,80.0,97.0,2021.0,3.0
22,64.000000,93.0,3.0,98.0,2018.0,3.0
23,0.000000,75.0,77.0,80.0,2018.0,2.0
24,72.000000,NaN,67.0,87.0,NaN,3.0
25,74.000000,87.0,72.0,98.0,2020.0,3.0
26,71.000000,78.0,72.0,78.0,NaN,2.0
27,72.000000,90.0,73.0,82.0,2021.0,2.0
28,72.000000,91.0,67.0,87.0,2020.0,3.0
29,65.000000,79.0,64.0,91.0,2019.0,3.0
30,73.000000,95.0,NaN,93.0,2019.0,3.0
31,62.000000,91.0,NaN,98.0,2019.0,3.0
32,76.000000,91.0,NaN,93.0,89.0,3.0
33,73.000000,84.0,72.0,90.0,2021.0,3.0
34,71.000000,92.0,67.0,89.0,2019.0,3.0
35,65.000000,85.0,78.0,81.0,2018.0,2.0
36,75.000000,95.0,77.0,99.0,2018.0,3.0
37,61.000000,76.0,73.0,97.0,2020.0,3.0
38,63.000000,79.0,76.0,86.0,3445.0,3.0
39,67.000000,5444.0,60.0,80.0,2020.0,2.0
40,70.000000,89.0,67.0,82.0,2020.0,2.0
41,61.000000,94.0,62.0,88.0,2021.0,3.0
42,64.000000,95.0,63.0,98.0,2020.0,NaN
43,69.000000,95.0,60.0,5.0,2019.0,NaN
44,69.000000,78.0,999.0,77.0,2019.0,NaN
45,62.000000,83.0,63.0,81.0,2020.0,NaN
46,68.000000,80.0,73.0,0.0,2019.0,1.0
47,73.000000,92.0,73.0,81.0,2019.0,2.0
48,74.000000,75.0,99.0,100.0,99.0,3.0
49,75.000000,76.0,0.0,80.0,2018.0,2.0

In [11]:
m_v=df['Reading_Score'].mean()
df['Reading_Score'].fillna(value=m_v, inplace=True) 
df

C:\Users\AJAY\AppData\Local\Temp\ipykernel_2352\1917897719.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Reading_Score'].fillna(value=m_v, inplace=True)

,Math_Score,Reading_Score,Writing_Score,Placement_Score,Club_Join_Date,Placement_Offer_Count
0,72.000000,84.000000,76.0,90.0,456.0,3.0
1,62.000000,82.000000,65.0,87.0,2019.0,3.0
2,58.000000,22.000000,0.0,83.0,2021.0,6.0
3,69.000000,45.000000,75.0,98.0,2021.0,3.0
4,99.000000,81.000000,64.0,80.0,NaN,2.0
5,63.000000,79.000000,79.0,91.0,2021.0,9.0
6,68.000000,78.000000,0.0,92.0,2020.0,3.0
7,68.000000,88.000000,80.0,79.0,90.0,2.0
8,65.844444,75.000000,62.0,86.0,2021.0,3.0
9,65.844444,85.000000,66.0,NaN,2018.0,2.0
10,68.000000,86.000000,66.0,80.0,999.0,2.0
11,65.844444,84.000000,72.0,77.0,2018.0,2.0
12,65.844444,94.000000,66.0,90.0,2020.0,3.0
13,34.000000,75.000000,66.0,95.0,0.0,0.0
14,75.000000,75.000000,72.0,96.0,2019.0,3.0
15,65.844444,83.000000,62.0,NaN,2021.0,2.0
16,60.000000,197.195652,73.0,NaN,2020.0,2.0
17,1.000000,76.000000,60.0,NaN,2020.0,3.0
18,80.000000,197.195652,65.0,NaN,2021.0,2.0
19,79.000000,93.000000,3.0,80.0,2021.0,2.0
20,79.000000,197.195652,76.0,77.0,2019.0,90.0
21,67.000000,4.000000,80.0,97.0,2021.0,3.0
22,64.000000,93.000000,3.0,98.0,2018.0,3.0
23,0.000000,75.000000,77.0,80.0,2018.0,2.0
24,72.000000,197.195652,67.0,87.0,NaN,3.0
25,74.000000,87.000000,72.0,98.0,2020.0,3.0
26,71.000000,78.000000,72.0,78.0,NaN,2.0
27,72.000000,90.000000,73.0,82.0,2021.0,2.0
28,72.000000,91.000000,67.0,87.0,2020.0,3.0
29,65.000000,79.000000,64.0,91.0,2019.0,3.0
30,73.000000,95.000000,NaN,93.0,2019.0,3.0
31,62.000000,91.000000,NaN,98.0,2019.0,3.0
32,76.000000,91.000000,NaN,93.0,89.0,3.0
33,73.000000,84.000000,72.0,90.0,2021.0,3.0
34,71.000000,92.000000,67.0,89.0,2019.0,3.0
35,65.000000,85.000000,78.0,81.0,2018.0,2.0
36,75.000000,95.000000,77.0,99.0,2018.0,3.0
37,61.000000,76.000000,73.0,97.0,2020.0,3.0
38,63.000000,79.000000,76.0,86.0,3445.0,3.0
39,67.000000,5444.000000,60.0,80.0,2020.0,2.0
40,70.000000,89.000000,67.0,82.0,2020.0,2.0
41,61.000000,94.000000,62.0,88.0,2021.0,3.0
42,64.000000,95.000000,63.0,98.0,2020.0,NaN
43,69.000000,95.000000,60.0,5.0,2019.0,NaN
44,69.000000,78.000000,999.0,77.0,2019.0,NaN
45,62.000000,83.000000,63.0,81.0,2020.0,NaN
46,68.000000,80.000000,73.0,0.0,2019.0,1.0
47,73.000000,92.000000,73.0,81.0,2019.0,2.0
48,74.000000,75.000000,99.0,100.0,99.0,3.0
49,75.000000,76.000000,0.0,80.0,2018.0,2.0

In [12]:
m_v=df['Placement_Score'].mean()
df['Placement_Score'].fillna(value=m_v, inplace=True) 
df

C:\Users\AJAY\AppData\Local\Temp\ipykernel_2352\318748052.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Placement_Score'].fillna(value=m_v, inplace=True)

,Math_Score,Reading_Score,Writing_Score,Placement_Score,Club_Join_Date,Placement_Offer_Count
0,72.000000,84.000000,76.0,90.000000,456.0,3.0
1,62.000000,82.000000,65.0,87.000000,2019.0,3.0
2,58.000000,22.000000,0.0,83.000000,2021.0,6.0
3,69.000000,45.000000,75.0,98.000000,2021.0,3.0
4,99.000000,81.000000,64.0,80.000000,NaN,2.0
5,63.000000,79.000000,79.0,91.000000,2021.0,9.0
6,68.000000,78.000000,0.0,92.000000,2020.0,3.0
7,68.000000,88.000000,80.0,79.000000,90.0,2.0
8,65.844444,75.000000,62.0,86.000000,2021.0,3.0
9,65.844444,85.000000,66.0,83.933333,2018.0,2.0
10,68.000000,86.000000,66.0,80.000000,999.0,2.0
11,65.844444,84.000000,72.0,77.000000,2018.0,2.0
12,65.844444,94.000000,66.0,90.000000,2020.0,3.0
13,34.000000,75.000000,66.0,95.000000,0.0,0.0
14,75.000000,75.000000,72.0,96.000000,2019.0,3.0
15,65.844444,83.000000,62.0,83.933333,2021.0,2.0
16,60.000000,197.195652,73.0,83.933333,2020.0,2.0
17,1.000000,76.000000,60.0,83.933333,2020.0,3.0
18,80.000000,197.195652,65.0,83.933333,2021.0,2.0
19,79.000000,93.000000,3.0,80.000000,2021.0,2.0
20,79.000000,197.195652,76.0,77.000000,2019.0,90.0
21,67.000000,4.000000,80.0,97.000000,2021.0,3.0
22,64.000000,93.000000,3.0,98.000000,2018.0,3.0
23,0.000000,75.000000,77.0,80.000000,2018.0,2.0
24,72.000000,197.195652,67.0,87.000000,NaN,3.0
25,74.000000,87.000000,72.0,98.000000,2020.0,3.0
26,71.000000,78.000000,72.0,78.000000,NaN,2.0
27,72.000000,90.000000,73.0,82.000000,2021.0,2.0
28,72.000000,91.000000,67.0,87.000000,2020.0,3.0
29,65.000000,79.000000,64.0,91.000000,2019.0,3.0
30,73.000000,95.000000,NaN,93.000000,2019.0,3.0
31,62.000000,91.000000,NaN,98.000000,2019.0,3.0
32,76.000000,91.000000,NaN,93.000000,89.0,3.0
33,73.000000,84.000000,72.0,90.000000,2021.0,3.0
34,71.000000,92.000000,67.0,89.000000,2019.0,3.0
35,65.000000,85.000000,78.0,81.000000,2018.0,2.0
36,75.000000,95.000000,77.0,99.000000,2018.0,3.0
37,61.000000,76.000000,73.0,97.000000,2020.0,3.0
38,63.000000,79.000000,76.0,86.000000,3445.0,3.0
39,67.000000,5444.000000,60.0,80.000000,2020.0,2.0
40,70.000000,89.000000,67.0,82.000000,2020.0,2.0
41,61.000000,94.000000,62.0,88.000000,2021.0,3.0
42,64.000000,95.000000,63.0,98.000000,2020.0,NaN
43,69.000000,95.000000,60.0,5.000000,2019.0,NaN
44,69.000000,78.000000,999.0,77.000000,2019.0,NaN
45,62.000000,83.000000,63.0,81.000000,2020.0,NaN
46,68.000000,80.000000,73.0,0.000000,2019.0,1.0
47,73.000000,92.000000,73.0,81.000000,2019.0,2.0
48,74.000000,75.000000,99.0,100.000000,99.0,3.0
49,75.000000,76.000000,0.0,80.000000,2018.0,2.0